### ISSUE TITLE
Integral Image type

### ISSUE THREAD

**Issue by mronian** [JuliaImages/ImagesFiltering.jl#4]
I'd like to do this the correct way as you envisioned. I looked at `MappedArrays` and `IndirectArrays` (I presume you meant the actual code itself for these packages as I could not find any docs). 

If I understood correctly, there will be an `IntegralImage{.....} <: AbstractArray` type and we will re-define some functions from Base and add some other ones to do what `boxdiff` and `integral_image` currently do. The constructor for this type will create the `integral_image`.

Also, should it assume that if `I` is an `IntegralImage` and one does `I[3:5, 4:10]` then they want the `boxdiff` or will that be confusing?

Another feature could be that if someone passes an `Image` type to the newer `boxdiff` then it automatically gets the integral image and returns the correct result.

**Comment by timholy** [comment]
>  (I presume you meant the actual code itself for these packages as I could not find any docs)

I did mean the code, but both of them do have a README.md. More docs needed?

> I is an IntegralImage and one does I[3:5, 4:10] then they want the boxdiff or will that be confusing?

This is an excellent question. Yes, this is what you want it to do but for all other AbstractArray types, indexing with ranges means something very different and I agree it would be quite confusing to break that rule.

How about defining indexing with `Intervals`? Some interesting discussion is [here](https://github.com/mbauman/AxisArrays.jl/issues/20), and I suspect the best (most minimal) package is https://github.com/scheinerman/ClosedIntervals.jl.

I wonder if it should be called `BoxMean` rather than `IntegralImage`. To decide what to call it, let me ask more about what it will be used for. Is there a use case for actually returning the value of the integral, or is the integral merely a means to efficient computation of the mean value over box-shaped regions? If the latter is the only way it will be used, then there is no good reason to use "Integral" in the name (it's an internal implementation detail) and we should deliberately not support indexing with `Int` and only support `Interval` indexing.

I think the interface would look something like this:
```jl
imgmean = BoxMean(img, dims)   # constructor; dims is optional, and dims not included are available only for slicing via `Int` indices
imgmean[3..5, 1..5]   # two intervals
imgmean[4±1, 3±2]  # another way of saying the same thing
imgmean[CartesianIndex((4,3))±1]
interpolate(imgmean, CartesianIndex((4,3))±0.5)  # fractional values throw an error for getindex but not interpolate
```

In this world, I don't think `boxdiff` would be a function anymore.

Also, I'd say it would be fine to get the version without `dims` implemented first and then we can add that later. It will be important for images with more than 2 dimensions; if someone is analyzing a movie, it's unlikely they want to integrate over time (although they might). Using `cumsum` and more likely `cumsum!`, I don't think there's any reason to limit this to 2d.

**Comment by kmsquire** [comment]
Haven't followed the conversation that closely, but "integral image" is the term used in CV literature, so I would probably stick with that, unless you're implementing something radically different. Cheers!

**Comment by timholy** [comment]
In that case I'm mostly fine with it.

**Comment by timholy** [comment]
It occurs to me that perhaps it would be better as a standalone package. I increasingly find that new AbstractArray types deserve their own package, since they tend to have a focused use that may have applications well beyond that envisioned by the original creator(s).

Maybe it should even be called `IntegralArrays.jl` (i.e. not necessarily with Image in the name). Not that I would be opposed to keeping Image in the name. Either way, of course it could be hosted here at JuliaImages if you like.

**Comment by mronian** [comment]
I second @kmsquire , Integral Image is more appropriate.

Regarding separate packages, I am just worried that so many small packages will lead to a mess later on when everything needs to be put in one package. I haven't done this before so just wanted to check with you if that would be easy, with each package having its own version/tag history. Instead we could have a `ImageTypes.jl` which will hold all such types which will be derived from `Image` itself since integral image would probably be always used in the context of image processing / computer vision.

**Comment by timholy** [comment]
Images will look like this:
```
@reexport using ImageCore
@reexport using ImageFiltering
@reexport using IntegralArray
...
```
The only part I'm unsure about is the documentation, but I am pretty sure even that will be straightforward.

The concept behind integral image is not unique to image processing; the idea of using the integral as a fast means for computing averages has a history going back to the beginning of the computing era.

**Comment by mronian** [comment]
Oh. That looks pretty clean! I'll make a package for `IntegralArray.jl` :)

**Comment by mronian** [comment]
We had used the `accum` function in Images.jl to check if the type needed to be promoted for the integral array in case of overflow. That was an internal function though. Anything similar to that in Base? Should we move `accum` to Base/ImageCore.jl?

**Comment by mronian** [comment]
Also, `coords_spatial`.

**Comment by timholy** [comment]
Yes, putting it in ImageCore would be good.
